[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.17"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
base_sepolia = "${SEPOLIA_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"

[etherscan]
# optional mapping; Foundry/forge CLI also chấp nhận --etherscan-api-key flag
base = { key = "${ETHERSCAN_API_KEY}" }
